# Dockerfile.web
FROM python:3.13-slim

WORKDIR /app

# Устанавливаем системные зависимости, необходимые для сборки драйвера PostgreSQL
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Устанавливаем python-зависимости, включая WSGI-сервер (gunicorn) и драйвер БД (psycopg2)
RUN pip install --no-cache-dir -r requirements.txt gunicorn psycopg2-binary

# Копируем весь исходный код проекта
COPY . .

# Запускаем gunicorn
CMD ["gunicorn", "waf_project.wsgi:application", "--bind", "0.0.0.0:8000"]