sonar.projectKey=testuserforcicd_testcicd
sonar.organization=testuserforcicd

# Указываем, что у нас Python и где лежит код
sonar.python.version=3.13
sonar.sources=.

# Исключаем из проверки пайплайны и прочий мусор
sonar.exclusions=**/venv/**, **/.github/**, **/*.html