# Generated by Django 6.0.3 on 2026-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_protectedsite_traffic_limit_mb_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedsite',
            name='target_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP-адрес сервера'),
        ),
    ]
