# Generated by Django 6.0.3 on 2026-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_protectedsite_target_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedsite',
            name='target_ip',
            field=models.CharField(max_length=100),
        ),
    ]
