# Generated by Django 6.0.3 on 2026-04-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_protectedsite_target_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bytes_in', models.BigIntegerField(default=0, verbose_name='Входящий трафик (байт)')),
                ('bytes_out', models.BigIntegerField(default=0, verbose_name='Исходящий трафик (байт)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_stats', to='accounts.protectedsite')),
            ],
            options={
                'verbose_name': 'Статистика трафика',
                'verbose_name_plural': 'Статистика трафика',
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
