# Generated by Django 6.0.3 on 2026-04-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_tariff_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rule_triggered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wafrule')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_attempts', to='accounts.protectedsite')),
            ],
            options={
                'verbose_name': 'Попытка атаки',
                'verbose_name_plural': 'Попытки атак',
                'indexes': [models.Index(fields=['site', 'ip_address', 'timestamp'], name='accounts_at_site_id_5865d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('attack_count', models.IntegerField(default=0, help_text='Количество атак перед баном')),
                ('time_window_minutes', models.IntegerField(default=10, help_text='Временное окно в минутах')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_ips', to='accounts.protectedsite')),
            ],
            options={
                'verbose_name': 'Забаненный IP',
                'verbose_name_plural': 'Забаненные IP',
                'indexes': [models.Index(fields=['site', 'ip_address', 'is_active', 'expires_at'], name='accounts_ba_site_id_35d629_idx')],
                'unique_together': {('site', 'ip_address')},
            },
        ),
    ]
